import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-sports-ticketing-settlement-reconciliation",
  "engine": "recovery",
  "title": "Sports Ticketing Settlement Reconciliation",
  "shortTitle": "Sports Ticketing Settlement Reconciliation",
  "tagline": "Reconcile ticket face value, fees, resale participation, refunds, taxes, and event-level partner settlements.",
  "industry": "Sports Revenue Assurance",
  "buyer": "Teams, venues, and ticketing platforms",
  "uiPort": 4737,
  "apiPort": 5737,
  "accent": "#15803d",
  "currency": "USD",
  "primaryOutcome": "Sports Ticketing Settlement Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash in one accountable workflow. Reconcile ticket face value, fees, resale participation, refunds, taxes, and event-level partner settlements.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Sports Ticketing Settlement Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("ticketing-agreement-library","STS01","Ticketing agreement library","Execute ticketing agreement library using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed ticketing agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Ticketing agreement library Reference","text","STS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("event-seat-inventory","STS02","Event seat inventory","Execute event seat inventory using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed event seat inventory decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Event seat inventory Reference","text","STS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("primary-sale-ingestion","STS03","Primary sale ingestion","Execute primary sale ingestion using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed primary sale ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Primary sale ingestion Reference","text","STS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("resale-transaction-ingestion","STS04","Resale transaction ingestion","Execute resale transaction ingestion using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed resale transaction ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Resale transaction ingestion Reference","text","STS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("face-value-reconciliation","STS05","Face value reconciliation","Execute face value reconciliation using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed face value reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Face value reconciliation Reference","text","STS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("service-fee-calculation","STS06","Service fee calculation","Execute service fee calculation using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed service fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Service fee calculation Reference","text","STS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("resale-participation","STS07","Resale participation","Execute resale participation using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed resale participation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Resale participation Reference","text","STS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("refund-cancellation-control","STS08","Refund cancellation control","Execute refund cancellation control using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed refund cancellation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Refund cancellation control Reference","text","STS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("chargeback-allocation","STS09","Chargeback allocation","Execute chargeback allocation using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed chargeback allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Chargeback allocation Reference","text","STS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("tax-settlement","STS10","Tax settlement","Execute tax settlement using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed tax settlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Tax settlement Reference","text","STS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("venue-promoter-split","STS11","Venue promoter split","Execute venue promoter split using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed venue promoter split decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Venue promoter split Reference","text","STS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("ticketing-statement-audit","STS12","Ticketing statement audit","Execute ticketing statement audit using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed ticketing statement audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Ticketing statement audit Reference","text","STS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("dispute-workflow","STS13","Dispute workflow","Execute dispute workflow using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Dispute workflow Reference","text","STS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("cash-reconciliation","STS14","Cash reconciliation","Execute cash reconciliation using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Cash reconciliation Reference","text","STS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]}),
feature("event-channel-analytics","STS15","Event channel analytics","Execute event channel analytics using ticketing agreements, events, seat inventories, primary sales, resale transactions, fees, refunds, chargebacks, taxes, partner shares, settlements, and cash.","Produce a governed event channel analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Event / Sales Channel","text","Event / Sales Channel · Standard Case"],["caseReference","Event channel analytics Reference","text","STS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1800000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2178000],["domainDriver","Sales Channel","select","Primary",["Primary","Verified resale","Group sales"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Ticketing agreement library case","Event seat inventory case","Primary sale ingestion case","Resale transaction ingestion case","Face value reconciliation case"]})
]);
